### ISSUE TITLE
Please add the `racket` GitHub topic 

### ISSUE THREAD

**Issue by spdegabrielle** [zyrolasting/polyglot#1]
Hi,
Please add the `racket` GitHub topic to this repo - I think others will be interested and this will help them find it at https://github.com/topics/racket
See https://help.github.com/en/articles/classifying-your-repository-with-topics for details of GitHub 'Topics'.
Kind regards,
Stephen

**Comment by zyrolasting** [comment]
Added. Hope this is helpful!
