### ISSUE TITLE
[Question] Integrating with Frog

### ISSUE THREAD

**Issue by pmatos** [zyrolasting/polyglot#11]
I absolutely love the polyglot idea but changing from Frog to polyglot to is a bit too much. Is there a way to integrate the way polyglot does things with Frog? So, instead of having a system which does the whole publishing, simply having a system that given a mixed-language markdown file outputs an html?

**Comment by zyrolasting** [comment]
@pmatos I am happy to provide a command that just outputs Rackdown to HTML, since that does seem useful. I'll work on that this weekend. Frog integration seems like it can happen in a lot of ways, so can you give me more of a breakdown on what the ideal workflow looks like for you?

**Comment by pmatos** [comment]
@zyrolasting I wouldn't worry about frog. I can do the frog side - actually have already started. I have a pre-enhance-body function which takes a path and returns a bunch of xexpr. This means that if I can get from you a function that either takes a path or the contents of a file and returns a bunch of processed xexpr integration is done.

**Comment by pmatos** [comment]
Thanks for this. It seems to be working. Writing a blog post to test this.
