### ISSUE TITLE
Internal contract broken

### ISSUE THREAD

**Issue by pmatos** [zyrolasting/polyglot#14]
Hi, I was having a problem with my blog and tracked it down to an issue with `run-txexpr!` when given a `txexpr?`.

Here's an interaction to explain the issue:
```
Welcome to Racket v7.4 [cs].
> (require polyglot)
> (run-txexpr! '(pre ((class "brush: console")) (code "$ Tools/Scripts/build-jsc --jsc-only --debug\n...\n====================================================================\n JavaScriptCore is now built (02m:44s). \n====================================================================")))
; get-tag: contract violation
;   expected: txexpr?
;   given: '((class "brush: console"))
;   in: the 1st argument of
;       (-> txexpr? txexpr-tag?)
;   contract from:
;       (/home/pmatos/.racket/7.4/pkgs/txexpr/txexpr/base.rkt
;        safe)
;   blaming: <pkgs>/polyglot/private/rkdown/scripts.rkt
;    (assuming the contract is correct)
;   at: <pkgs>/txexpr/txexpr/base.rkt:159.22
; [,bt for context]
```

But:
```
> (require txexpr)
> (txexpr? '(pre ((class "brush: console")) (code "$ Tools/Scripts/build-jsc --jsc-only --debug\n...\n====================================================================\n JavaScriptCore is now built (02m:44s). \n====================================================================")))
#t
```

So, the values `'(pre ((class "brus...` is a valid txexpr but `run-texpr!` chokes on it with an internal error.

**Comment by zyrolasting** [comment]
From [the relevant docs](https://docs.racket-lang.org/polyglot/Writing_Custom_Workflows.html?q=polyglot): 

```
(run-txexpr! tx-expressions [initial-layout])
  → (or/c (listof txexpr?) txexpr?)
  tx-expressions : (non-empty-listof txexpr?)
```

Running `(run-txexpr! '(pre ...))` breaks because `'(pre)` is not a list of tagged X-expressions. Wrapping another pair of parens gives me correct output.

**Comment by pmatos** [comment]
The issue was opened because the internal contract was broken instead of a contract with a user facing function name. The user knows nothing about `get-tag`. The contract should point the blame to the user passing a `txexpr?` instead of `(listof txexpr?)`.

**Comment by pmatos** [comment]
Ah, it seems #17 changed it. Thanks
