### ISSUE TITLE
Dependency discovery for <picture> srcset attribute

### ISSUE THREAD

**Issue by xy2iii** [zyrolasting/polyglot#39]
The [picture tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) allows including multiple image sources. To specify each source, the `srcset` attribute is used in a nested `source` element within the `picture` tag.

polyglot does not seek these tags because the attribute is named `srcset` and not `src`, leading to paths being left untouched. It would be useful to have to include multiple image sources, for example, webp images with png fallbacks, for the sake of browser compability.

**Comment by zyrolasting** [comment]
Happy Holidays! See #40
