### ISSUE TITLE
Contract of run-txexpr/imperative! incorrect

### ISSUE THREAD

**Issue by pmatos** [zyrolasting/polyglot#49]
I think this contract is incorrect.

https://github.com/zyrolasting/polyglot/blob/4014a1ae70520a442d8efe71a139bb4b07240ac7/polyglot-lib/polyglot/imperative.rkt#L15

I was indeed expecting a list of `txexpr?` but that's not the case:
```
> (run-txexpr/imperative! '((p () "What is superoptimization? What is S10? Here is an overview.")))
'(p "What is superoptimization? What is S10? Here is an overview.")
```

I couldn't find a way to enable contracts in polyglot but I am pretty sure this contract will break. Anyway, is it the case the a single `txexpr?` will be returned if the input list has a single `txexpr?`. Somehow I find that counter-intuitive. I would expect a list with as many elements I gave it to `run-txexpr!`.

**Comment by zyrolasting** [comment]
Thanks for finding this. `run-txexpr/imperative!` gives you control over the return value, but I did not factor in the default (no layout) case correctly. See if #50 behaves better for you.

**Comment by pmatos** [comment]
Feel free to close this when you merge #50, thanks.
