### ISSUE TITLE
bash: polyglot: command not found after installing on Debian 10

### ISSUE THREAD

**Issue by jerzybrzoska** [zyrolasting/polyglot#52]
I ran the following:
``
sudo raco pkg install polyglot 
``
The progress of the installation: 

>Resolving "polyglot" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "polyglot" via https://pkgs.racket-lang.org
Downloading repository https://github.com/zyrolasting/polyglot.git?path=polyglot
The following uninstalled packages are listed as dependencies of polyglot:
   polyglot-lib
   polyglot-doc
Would you like to install these dependencies? [Y/n/a/c/?] y
00: Resolving "polyglot-lib" via https://download.racket-lang.org/releases/7.2/catalog/
00: Resolving "polyglot-lib" via https://pkgs.racket-lang.org
Resolving "polyglot-doc" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "polyglot-doc" via https://pkgs.racket-lang.org
Using cached15992179021599217902139 for https://github.com/zyrolasting/polyglot.git?path=polyglot-lib
Using cached15992179021599217902139 for https://github.com/zyrolasting/polyglot.git?path=polyglot-doc
The following uninstalled packages are listed as dependencies of polyglot-lib:
   file-watchers
   txexpr
   unlike-assets-lib
   aws
   markdown
Would you like to install these dependencies? [Y/n/a/c/?] y
00: Resolving "file-watchers" via https://download.racket-lang.org/releases/7.2/catalog/
01: Resolving "txexpr" via https://download.racket-lang.org/releases/7.2/catalog/
02: Resolving "unlike-assets-lib" via https://download.racket-lang.org/releases/7.2/catalog/
03: Resolving "aws" via https://download.racket-lang.org/releases/7.2/catalog/
01: Resolving "txexpr" via https://pkgs.racket-lang.org
00: Resolving "file-watchers" via https://pkgs.racket-lang.org
03: Resolving "aws" via https://pkgs.racket-lang.org
02: Resolving "unlike-assets-lib" via https://pkgs.racket-lang.org
Resolving "markdown" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "markdown" via https://pkgs.racket-lang.org
Downloading repository https://github.com/zyrolasting/file-watchers.git
Downloading repository https://github.com/mbutterick/txexpr.git
Downloading repository https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-lib#7fb08d6902d34399c96a325d6d27f1ff84813b
Downloading repository github://github.com/greghendershott/aws/master
Downloading repository git://github.com/greghendershott/markdown
The following uninstalled packages are listed as dependencies of polyglot-doc:
   css-expr
   unlike-assets-doc
Would you like to install these dependencies? [Y/n/a/c/?] y
02: Resolving "css-expr" via https://download.racket-lang.org/releases/7.2/catalog/
02: Resolving "css-expr" via https://pkgs.racket-lang.org
Resolving "unlike-assets-doc" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "unlike-assets-doc" via https://pkgs.racket-lang.org
Downloading repository https://github.com/leafac/css-expr.git
Using cached15992179181599217918089 for https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-doc#7fb08d6902d34399c96a325d6d27f1ff84813b
The following uninstalled packages are listed as dependencies of txexpr:
   sugar
Would you like to install these dependencies? [Y/n/a/c/?] y
Resolving "sugar" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "sugar" via https://pkgs.racket-lang.org
Downloading repository https://github.com/mbutterick/sugar.git
The following uninstalled packages are listed as dependencies of unlike-assets-lib:
   ansi-color
   graph-lib
   kinda-ferpy
Would you like to install these dependencies? [Y/n/a/c/?] y
02: Resolving "ansi-color" via https://download.racket-lang.org/releases/7.2/catalog/
00: Resolving "graph-lib" via https://download.racket-lang.org/releases/7.2/catalog/
00: Resolving "graph-lib" via https://pkgs.racket-lang.org
02: Resolving "ansi-color" via https://pkgs.racket-lang.org
Resolving "kinda-ferpy" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "kinda-ferpy" via https://pkgs.racket-lang.org
Downloading repository https://github.com/renatoathaydes/ansi-color.git
Downloading repository https://github.com/stchang/graph.git?path=graph-lib
Downloading repository https://github.com/zyrolasting/kinda-ferpy.git
The following uninstalled packages are listed as dependencies of aws:
   http
   sha
Would you like to install these dependencies? [Y/n/a/c/?] y
02: Resolving "http" via https://download.racket-lang.org/releases/7.2/catalog/
02: Resolving "http" via https://pkgs.racket-lang.org
Resolving "sha" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "sha" via https://pkgs.racket-lang.org
Downloading repository git://github.com/greghendershott/http
Downloading repository github://github.com/greghendershott/sha/master
The following uninstalled packages are listed as dependencies of markdown:
   parsack
   threading-lib
   sexp-diff
Would you like to install these dependencies? [Y/n/a/c/?] Y
02: Resolving "parsack" via https://download.racket-lang.org/releases/7.2/catalog/
00: Resolving "threading-lib" via https://download.racket-lang.org/releases/7.2/catalog/
02: Resolving "parsack" via https://pkgs.racket-lang.org
00: Resolving "threading-lib" via https://pkgs.racket-lang.org
Resolving "sexp-diff" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "sexp-diff" via https://pkgs.racket-lang.org
Downloading repository github://github.com/stchang/parsack/master/
Downloading repository git://github.com/lexi-lambda/threading?path=threading-lib
Downloading repository https://github.com/stamourv/sexp-diff.git
The following uninstalled packages are listed as dependencies of css-expr:
   nanopass
Would you like to install these dependencies? [Y/n/a/c/?] y
Resolving "nanopass" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "nanopass" via https://pkgs.racket-lang.org
Downloading repository git://github.com/nanopass/nanopass-framework-racket
The following uninstalled packages are listed as dependencies of graph-lib:
   gen-queue-lib
Would you like to install these dependencies? [Y/n/a/c/?] y
Resolving "gen-queue-lib" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "gen-queue-lib" via https://pkgs.racket-lang.org
Using cached15992179551599217955058 for https://github.com/stchang/graph.git?path=gen-queue-lib
The following uninstalled packages are listed as dependencies of nanopass:
   unstable-pretty-lib
Would you like to install these dependencies? [Y/n/a/c/?] y
Resolving "unstable-pretty-lib" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "unstable-pretty-lib" via https://pkgs.racket-lang.org
Downloading repository git://github.com/racket/unstable-pretty-lib
The following uninstalled packages were listed as dependencies
and they were installed:
 dependencies of polyglot:
   polyglot-lib
   polyglot-doc
 dependencies of polyglot-lib:
   file-watchers
   txexpr
   unlike-assets-lib
   aws
   markdown
 dependencies of polyglot-doc:
   css-expr
   unlike-assets-doc
 dependencies of txexpr:
   sugar
 dependencies of unlike-assets-lib:
   ansi-color
   graph-lib
   kinda-ferpy
 dependencies of aws:
   http
   sha
 dependencies of markdown:
   parsack
   threading-lib
   sexp-diff
 dependencies of css-expr:
   nanopass
 dependencies of graph-lib:
   gen-queue-lib
 dependencies of nanopass:
   unstable-pretty-lib
raco setup: version: 7.2
raco setup: platform: x86_64-linux [3m]
raco setup: target machine: racket
raco setup: installation name: 7.2
raco setup: variants: 3m
raco setup: main collects: /usr/share/racket/collects
raco setup: collects paths: 
raco setup:   /root/.racket/7.2/collects
raco setup:   /usr/share/racket/collects
raco setup: main pkgs: /usr/share/racket/pkgs
raco setup: pkgs paths: 
raco setup:   /usr/share/racket/pkgs
raco setup:   /root/.racket/7.2/pkgs
raco setup: links files: 
raco setup:   /usr/share/racket/links.rktd
raco setup:   /root/.racket/7.2/links.rktd
raco setup: main docs: /usr/share/doc/racket
raco setup: --- updating info-domain tables ---
raco setup: updating: /root/.racket/7.2/share/info-cache.rktd
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 2 jobs ---
raco setup: 1 making: <pkgs>/ansi-color
raco setup: 0 making: <pkgs>/aws/aws
raco setup: 1 making: <pkgs>/ansi-color/scribblings
raco setup: 1 making: <pkgs>/aws/examples
raco setup: 1 making: <pkgs>/css-expr
raco setup: 0 making: <pkgs>/aws/aws/tests
raco setup: 0 making: <pkgs>/aws/aws/vendor
raco setup: 0 making: <pkgs>/aws/aws/vendor/aws4_testsuite
raco setup: 0 making: <pkgs>/file-watchers
raco setup: 0 making: <pkgs>/file-watchers/scribblings
raco setup: 0 making: <pkgs>/gen-queue-lib/data
raco setup: 0 making: <pkgs>/gen-queue-lib/data/gen-queue
raco setup: 0 making: <pkgs>/graph-lib/graph
raco setup: 0 making: <pkgs>/http/http
raco setup: 0 making: <pkgs>/kinda-ferpy
raco setup: 0 making: <pkgs>/kinda-ferpy/scribblings
raco setup: 0 making: <pkgs>/markdown/markdown
raco setup: 1 making: <pkgs>/nanopass
raco setup: 1 making: <pkgs>/nanopass/lang
raco setup: 1 making: <pkgs>/nanopass/private
raco setup: 1 making: <pkgs>/nanopass/scribblings
raco setup: 1 making: <pkgs>/nanopass/tests
raco setup: 0 making: <pkgs>/parsack/parsack (parsack)
raco setup: 0 making: <pkgs>/parsack/parsack/examples
raco setup: 0 making: <pkgs>/parsack/parsack/examples/tests
raco setup: 0 making: <pkgs>/parsack/parsack/tests
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot/scribblings
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot/scribblings/guide
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot/scribblings/how-tos
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot/scribblings/reference
raco setup: 0 making: <pkgs>/polyglot-doc/polyglot/scribblings/tutorials
raco setup: 0 making: <pkgs>/polyglot-lib/polyglot
raco setup: 0 making: <pkgs>/polyglot-lib/polyglot/private
raco setup: 0 making: <pkgs>/polyglot-lib/polyglot/private/cli
raco setup: 1 making: <pkgs>/sexp-diff/sexp-diff
raco setup: 1 making: <pkgs>/sha/sha
raco setup: 0 making: <pkgs>/sugar/sugar
raco setup: 1 making: <pkgs>/threading-lib/threading
raco setup: 1 making: <pkgs>/txexpr/txexpr
raco setup: 1 making: <pkgs>/txexpr/txexpr/private
raco setup: 1 making: <pkgs>/txexpr/txexpr/scribblings
raco setup: 1 making: <pkgs>/txexpr/txexpr/test
raco setup: 0 making: <pkgs>/sugar/sugar/coerce
raco setup: 1 making: <pkgs>/txexpr/txexpr/unstable
raco setup: 1 making: <pkgs>/unlike-assets-doc/unlike-assets
raco setup: 1 making: <pkgs>/unlike-assets-doc/unlike-assets/scribblings
raco setup: 0 making: <pkgs>/sugar/sugar/private
raco setup: 0 making: <pkgs>/sugar/sugar/scribblings
raco setup: 0 making: <pkgs>/sugar/sugar/unstable
raco setup: 1 making: <pkgs>/unlike-assets-lib/unlike-assets
raco setup: 1 making: <pkgs>/unlike-assets-lib/unlike-assets/private
raco setup: 1 making: <pkgs>/unlike-assets-lib/unlike-assets/private/reactive
raco setup: 1 making: <pkgs>/unstable-pretty-lib/unstable
raco setup: --- creating launchers ---
raco setup: launcher: /root/.racket/7.2/bin/polyglot
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: 0 running: <pkgs>/ansi-color/scribblings/ansi-color.scrbl
raco setup: 1 running: <pkgs>/aws/aws/aws.scrbl
raco setup: 0 running: <pkgs>/css-expr/css-expr.scrbl
raco setup: 1 running: <pkgs>/file-watchers/scribblings/file-watchers.scrbl
raco setup: 1 running: <pkgs>/http/http/http.scrbl
raco setup: 1 running: <pkgs>/kinda-ferpy/scribblings/kinda-ferpy.scrbl
raco setup: 1 running: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 1 running: <pkgs>/markdown/markdown/markdown.scrbl
raco setup: 1 running: <pkgs>/nanopass/scribblings/nanopass.scrbl
raco setup: 1 running: <pkgs>/parsack/parsack/parsack.scrbl
raco setup: 0 running: <pkgs>/polyglot-doc/polyglot/scribblings/guide/polyglot-guide.scrbl
raco setup: 1 running: <pkgs>/polyglot-doc/polyglot/scribblings/how-tos/polyglot-how-tos.scrbl
raco setup: 0 running: <pkgs>/polyglot-doc/polyglot/scribblings/reference/polyglot-reference.scrbl
raco setup: 1 running: <pkgs>/polyglot-doc/polyglot/scribblings/tutorials/polyglot-tutorials.scrbl
raco setup: 1 running: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 0 running: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 1 running: <pkgs>/sexp-diff/sexp-diff/sexp-diff.scrbl
raco setup: 0 running: <pkgs>/sha/sha/sha.scrbl
raco setup: 0 running: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: 1 running: <pkgs>/sugar/sugar/scribblings/sugar.scrbl
raco setup: 0 running: <pkgs>/txexpr/txexpr/scribblings/txexpr.scrbl
raco setup: 0 running: <pkgs>/unlike-assets-doc/unlike-assets/scribblings/unlike-assets.scrbl
raco setup: WARNING: undefined tag in <pkgs>/ansi-color/scribblings/ansi-color.scrbl:
raco setup:  ((lib "ansi-color/main.rkt") ansi-color?)
raco setup: 1 rendering: <pkgs>/ansi-color/scribblings/ansi-color.scrbl
raco setup: 0 rendering: <pkgs>/aws/aws/aws.scrbl
raco setup: 1 rendering: <pkgs>/css-expr/css-expr.scrbl
raco setup: 0 rendering: <pkgs>/file-watchers/scribblings/file-watchers.scrbl
raco setup: 0 rendering: <pkgs>/http/http/http.scrbl
raco setup: 0 rendering: <pkgs>/kinda-ferpy/scribblings/kinda-ferpy.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 0 rendering: <pkgs>/markdown/markdown/markdown.scrbl
raco setup: 0 rendering: <pkgs>/nanopass/scribblings/nanopass.scrbl
raco setup: 1 rendering: <pkgs>/parsack/parsack/parsack.scrbl
raco setup: 0 rendering: <pkgs>/polyglot-doc/polyglot/scribblings/guide/polyglot-guide.scrbl
raco setup: 1 rendering: <pkgs>/polyglot-doc/polyglot/scribblings/how-tos/polyglot-how-tos.scrbl
raco setup: 0 rendering: <pkgs>/polyglot-doc/polyglot/scribblings/reference/polyglot-reference.scrbl
raco setup: 1 rendering: <pkgs>/polyglot-doc/polyglot/scribblings/tutorials/polyglot-tutorials.scrbl
raco setup: 1 rendering: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 1 rendering: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 0 rendering: <pkgs>/sexp-diff/sexp-diff/sexp-diff.scrbl
raco setup: 1 rendering: <pkgs>/sha/sha/sha.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: 1 rendering: <pkgs>/sugar/sugar/scribblings/sugar.scrbl
raco setup: 0 rendering: <pkgs>/txexpr/txexpr/scribblings/txexpr.scrbl
raco setup: 0 rendering: <pkgs>/unlike-assets-doc/unlike-assets/scribblings/unlike-assets.scrbl
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---

``polyglot demo``   gives me 

> bash: polyglot: command not found

``which polyglot`` gives me no result. It seems that installation failed. 
My environment:
Debian 10.

What could be the reason of this issue? How can I resolve this issue?

**Comment by zyrolasting** [comment]
The installation looks like it went fine, but I believe the `polyglot` command was not installed in your normal user's `PATH` because of the `sudo` command. Are you not able to install `polyglot` with normal user privileges? If so, does it work then?

**Comment by jerzybrzoska** [comment]
>  Are you not able to install `polyglot` with normal user privileges? If so, does it work then?
I am. 
I ran ``raco pkg remove polyglot`` and ``sudo apt --purge remove racket`` in order to have a clean slate and start anew.
Then I installled racket, a consequently ran:
``raco pkg install polyglot`` 
This time I got somewhat shorter feedback from raco - I was not asket to install any dependencies:
>Resolving "polyglot" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "polyglot" via https://pkgs.racket-lang.org
Using cached15992168771599216877892 for https://github.com/zyrolasting/polyglot.git?path=polyglot
Resolving "polyglot-lib" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "polyglot-lib" via https://pkgs.racket-lang.org
Resolving "polyglot-doc" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "polyglot-doc" via https://pkgs.racket-lang.org
raco setup: version: 7.2
raco setup: platform: x86_64-linux [3m]
raco setup: target machine: racket
raco setup: installation name: 7.2
raco setup: variants: 3m
raco setup: main collects: /usr/share/racket/collects
raco setup: collects paths: 
raco setup:   /home/jerzy/.racket/7.2/collects
raco setup:   /usr/share/racket/collects
raco setup: main pkgs: /usr/share/racket/pkgs
raco setup: pkgs paths: 
raco setup:   /usr/share/racket/pkgs
raco setup:   /home/jerzy/.racket/7.2/pkgs
raco setup: links files: 
raco setup:   /usr/share/racket/links.rktd
raco setup:   /home/jerzy/.racket/7.2/links.rktd
raco setup: main docs: /usr/share/doc/racket
raco setup: --- updating info-domain tables ---
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 2 jobs ---
raco setup: --- creating launchers ---
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---

Yet, all this to no avail. polyglot demo gives me

>bash: polyglot: command not found

which polyglot gives me no result.

**Comment by zyrolasting** [comment]
Okay, then your `PATH` might not include the directory in which launchers are created. It looks like you might have a Unix-style installation since docs are appearing in `/usr/share`. Check your different binary directories (e.g. `/bin` `/usr/bin` `usr/local/bin`) to see if `polyglot` appears in one of them. If so, add that directory to your `PATH`.

**Comment by zyrolasting** [comment]
Closing this since I haven't heard back. Please reopen if you are still having an issue
